{{ $properties := (datasource "properties") }}
{{ $project := (datasource "project") }}
{{ $dependency := (datasource "dependency") }}
{{ $connectors := (datasource "connectors") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $properties.localName }}
  namespace: {{ $project.namespace }}
  annotations:
    cloudfairy.dev/project-id: {{ $project.name }}
  labels:
    app: {{ $properties.localName }}
spec:
  replicas: 1
  selector:
   matchLabels:
    app: {{ $properties.localName }}
  template:
    metadata:
     labels:
       app: {{ $properties.localName }}
    spec:
     containers:
      - name: {{ $properties.localName }}
        image: {{ $properties.image_name }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ $properties.container_port }}
            protocol: TCP
        resources:
         limits:
            cpu: "{{ $properties.resource_cpu }}"
            memory: "512Mi"
        env: {{ range $key, $value := $properties.env_vars }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
        {{ end -}}
        {{- range $connector_type, $connector_list := $connectors -}}
        {{- if or (eq $connector_type "cloudfairy_docker_to_docker") (eq $connector_type "cloudfairy_docker_to_postgres") -}}
        {{- range $map := $connector_list -}}
        {{- range $name, $value := $map }}
          - name: "{{ $name }}"
            value: "{{ $value }}"
        {{ end -}}
        {{- end -}}
        {{- end -}}
        {{- end }}
