apiVersion: cloudfairy.dev/v1
kind: CloudfairyLibraryModule
metadata:
  namespace: example
  name: docker-container
spec:
  vendor: cloudfairy
  displayName: Docker (External Registry)
  dependencies: []
  interface:
    - env
  entry:
    default: ./manifests
  validation:
    - kind: query
      name: "Check Deployment"
      query: "deployment/{{ properties.localName }}"
      condition: "{{status.availableReplicas}} >= 1"
      timeout: 60000 # 60 seconds
    - kind: query
      name: "Check Service"
      query: "service/{{ properties.localName }}-svc"
      condition: 'typeof {{status.loadBalancer}} !== "undefined"'
      timeout: 60000 # 60 seconds
  output:
    - name: serviceName
      query: "service/{{ properties.localName }}-svc"
      value: "{{metadata.name}}"
    - name: servicePort
      query: "service/{{ properties.localName }}-svc"
      value: "{{spec.ports[0].port}}"
    - name: availabilty
      query: "deployment/{{ properties.localName }}"
      value: "{{status.availableReplicas}}"
  properties:
    - name: image_name
      displayName: "DockerHub Image or Image uri (incl. tag)"
      type: string
      defaultValue: nginx
    - name: container_port
      displayName: "Container Port"
      type: string
      defaultValue: "8080"
    - name: debug_port
      displayName: "Debug Port (-1 for none)"
      type: string
      defaultValue: "-1"
    - name: is_exposed
      displayName: "Expose Container?"
      type: boolean
      defaultValue: true
    - name: resource_cpu
      displayName: "Resource CPU"
      type: options
      options:
        - label: "0.5 vCPU"
          value: "500m"
          hint: "Low resources"
        - label: "1 vCPU"
          value: "1000m"
        - label: "2 vCPU"
          value: "2000m"
        - label: "4 vCPU"
          value: "4Gi"
          hint: "High resources"
      defaultValue: "500m"
    - name: env_vars
      displayName: "Extra Environment Variables"
      type: keyvalue
      defaultValue:
        cloudfairy: "true"
