{{ $properties := (datasource "properties") }}
{{ $project := (datasource "project") }}
{{ $dependency := (datasource "dependency") }}
{{ $connectors := (datasource "connectors") }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $properties.localName }}-pvc"
  namespace: "{{ $project.namespace }}"
  annotations:
    cloudfairy.dev/project-id: "{{ $project.name }}"
  labels:
    app: "{{ $properties.localName }}"
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ $properties.storage_size }}"