apiVersion: cloudfairy.dev/v1
kind: CloudfairyLibraryModule
metadata:
  name: docker-to-docker
  namespace: cloudfairy
  annotations:
    cloudfairy.dev/is-connector: "true"
spec:
  from:
    - example/docker-container
  to:
    - example/docker-container
  vendor: example
  displayName: Docker to Docker Connector
  dependecies: []
  interace: []
  validation: []
  output:
    - name: "{{ properties.env_host_name }}"
      value: "{{ dependency.to_module.serviceName }}"
    - name: "{{ properties.env_port_name }}"
      value: "{{ dependency.to_module.servicePort }}"
  properties:
    - name: env_host_name
      displayName: "Evironment variable for Host Name"
      type: string
      defaultValue: "SVC_HOST"
    - name: env_port_name
      displayName: "Evironment variable for Port"
      type: string
      defaultValue: "SVC_PORT"
