apiVersion: cloudfairy.dev/v1
kind: CloudfairyLibraryModule
metadata:
  name: postgres
  namespace: cloudfairy
spec:
  vendor: example
  displayName: PostgreSQL
  dependencies: []
  interface:
    - cloudfairy.dev/with-service
    - cloudfairy.dev/with-user-and-password
  entry:
    default: ./manifests
    gcp: ./gcp
  validation: []
  output:
    - name: serviceName
      query: "service/{{ properties.localName }}-svc"
      value: "{{metadata.name}}"
    - name: servicePort
      query: "service/{{ properties.localName }}-svc"
      value: "{{spec.ports[0].port}}"
    - name: user
      query: "configmap/{{ properties.localName }}-secret"
      value: "{{ data.POSTGRES_USER }}"
    - name: password
      query: "configmap/{{ properties.localName }}-secret"
      value: "{{ data.POSTGRES_PASSWORD }}"
  properties:
    - name: storage_size
      displayName: "Storage Size"
      type: options
      defaultValue: "10Gi"
      options:
        - label: "10Gb"
          value: "10Gi"
        - label: "20Gb"
          value: "20Gi"
        - label: "50Gb"
          value: "50Gi"
        - label: "100Gb"
          value: "1000Gi"
