apiVersion: cloudfairy.dev/v1
kind: CloudfairyLibraryModule
metadata:
  name: postgres
  namespace: cloudfairy
spec:
  vendor: example
  displayName: PostgreSQL
  dependencies: []
  interface:
    - env
  entry:
    default: ./manifests
  validation: []
  output:
    - name: serviceName
      query: "service/{{ properties.localName }}-svc"
      value: "{{metadata.name}}"
    - name: servicePort
      query: "service/{{ properties.localName }}-svc"
      value: "{{spec.ports[0].port}}"
    - name: user
      query: "configmap/{{ properties.localName }}-secret"
      value: "{{ data.POSTGRES_USER }}"
    - name: password
      query: "configmap/{{ properties.localName }}-secret"
      value: "{{ data.POSTGRES_PASSWORD }}"
  properties:
    - name: storage_size
      displayName: "Storage Size"
      type: options
      defaultValue: "10Gi"
      options:
        - label: "10Gb"
          value: "10Gi"
        - label: "20Gb"
          value: "20Gi"
        - label: "50Gb"
          value: "50Gi"
        - label: "100Gb"
          value: "1000Gi"

---
apiVersion: cloudfairy.dev/v1
kind: CloudfairyLibraryModule
metadata:
  name: docker-to-postgres
  namespace: cloudfairy
  annotations:
    cloudfairy.dev/is-connector: "true"
spec:
  from:
    - cloudfairy/docker-container
  to:
    - cloudfairy/postgres
  vendor: example
  displayName: Docker to Postgres Connector
  dependecies: []
  interace: []
  validation: []
  output:
    - name: "{{ properties.env_host_name }}"
      value: "{{ dependency.to_module.serviceName }}"
    - name: "{{ properties.env_port_name }}"
      value: "5432"
    - name: "{{ properties.env_user }}"
      value: "{{ dependency.to_module.user }}"
    - name: "{{ properties.env_password }}"
      value: "{{ dependency.to_module.password }}"
  properties:
    - name: env_host_name
      displayName: "Evironment variable for Host Name"
      type: string
      defaultValue: "DB_HOST"
    - name: env_port_name
      displayName: "Evironment variable for Port"
      type: string
      defaultValue: "DB_PORT"
    - name: env_user
      displayName: "Evironment variable for Database user"
      type: string
      defaultValue: "DB_USER"
    - name: env_password
      displayName: "Evironment variable for Database password"
      type: string
      defaultValue: "DB_PASS"
