{{- $properties := (datasource "properties") -}}
{{- $project := (datasource "project") -}}
{{- $dependency := (datasource "dependency") -}}
{{- $connectors := (datasource "connectors") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $properties.localName }}-svc
  namespace: {{ $project.namespace }}
  annotations:
    cloudfairy.dev/project-id: {{ $project.name }}
  labels:
    app: {{ $properties.localName }}
spec:
  selector:
    app: {{ $properties.localName }}
  ports:
    - protocol: TCP
      port: {{ $properties.container_port }}
      name: "container-port"
      targetPort: {{ $properties.container_port }}
{{- if eq $properties.additional_port "-1" }}
    # No additional port
{{- else }}
    # Additional port
    - protocol: TCP
      port: {{ $properties.additional_port }}
      name: "additional-port"
      targetPort: {{ $properties.additional_port }}
{{- end }}
{{- if eq $properties.debug_port "-1" }}
    # No debug port
{{- else }}
    # Debug port
    - protocol: TCP
      port: {{ $properties.debug_port }}
      name: "debug-port"
      targetPort: {{ $properties.debug_port }}
{{- end }}
  type: NodePort
{{- if eq $properties.is_exposed true }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $properties.localName }}-ingress"
  namespace: {{ $project.namespace }}
spec:
  rules:
    - host: "{{ $properties.localName }}.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ $properties.localName }}-svc"
                port:
                  number: {{ $properties.container_port }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ $properties.localName }}-svc"
                port:
                  number: {{ $properties.container_port }}
{{- if (ne $properties.debug_port "-1") }}
    - host: "{{ $properties.localName }}.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ $properties.localName }}-svc"
                port:
                  number: {{ $properties.debug_port }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ $properties.localName }}-svc"
                port:
                  number: {{ $properties.debug_port }}
{{- end }}
{{- if (ne $properties.additional_port "-1") }}
    - host: "{{ $properties.localName }}.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ $properties.localName }}-svc"
                port:
                  number: {{ $properties.additional_port }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ $properties.localName }}-svc"
                port:
                  number: {{ $properties.additional_port }}
{{- end -}}
{{- end -}}